### ISSUE TITLE
Payload not displayed when only adding array of dictionaries payload

### ISSUE THREAD

**Issue by wegotoeleven** [ProfileCreator/ProfileManifests#155]
In my two recent commits of manifests for Motion and Compressor, when only adding in one array of dictionaries, the payload isn't displayed in the GUI. If a second payload is added (for example, a generic boolean payload), then the array of dictionaries is visible. 

The two previous PRs that this can be seen in are:

https://github.com/ProfileCreator/ProfileManifests/pull/154
https://github.com/ProfileCreator/ProfileManifests/pull/153

**Comment by apizz** [comment]
I'm not seeing this behavior.  On 10.14.6 with the current beta.

![Screen Shot 2020-04-11 at 12 52 02 PM](https://user-images.githubusercontent.com/11789931/79049728-5a459380-7bf3-11ea-87b3-aea1590b4cf0.png)
![Screen Shot 2020-04-11 at 12 52 05 PM](https://user-images.githubusercontent.com/11789931/79049732-5e71b100-7bf3-11ea-8de5-2611dae99189.png)
![Screen Shot 2020-04-11 at 12 52 29 PM](https://user-images.githubusercontent.com/11789931/79049735-603b7480-7bf3-11ea-84fe-b29e9131a2ab.png)
![Screen Shot 2020-04-11 at 12 52 31 PM](https://user-images.githubusercontent.com/11789931/79049740-63366500-7bf3-11ea-8e7c-4b60fb104b90.png)

However, it appears that since Motion in addition to having the dictionary preference with the version number as the key that there is a boolean preference as well.  Without another concrete pref which doesn't use `{{name}}` and `{{value}}`, as is the case with Compressor, nothing is shown in the GUI.

![Screen Shot 2020-04-11 at 12 53 25 PM](https://user-images.githubusercontent.com/11789931/79049751-721d1780-7bf3-11ea-8972-e615310cf622.png)

To fix this, I'm just going to add the same Motion boolean preference to Compressor.

**Comment by apizz** [comment]
Made the added preference hidden so the dictionary shows up correctly without adding a preference that is unknown to be present in the Compressor options.  Quit & reopen ProfileCreator to get the latest manifests.
