### ISSUE TITLE
Request for consideration of merging back split manifests

### ISSUE THREAD

**Issue by relgit** [ProfileCreator/ProfileManifests#182]
All,

Certain configuration domains (e.g. MCX, Restrictions) are split into multiple manifest files. I'd like to point out a technical issue with that, and to suggest that we consider merging these domains back.

For example, the Restrictions domain (`com.apple.applicationaccess`) is split into three platform-oriented manifest files. This is done to reduce clutter and works well when editing and then writing out a profile.

A problem exist with this approach when _loading_ profile files. A software consuming configuration profiles (e.g. _ProfileCreator_, _iMazing Profile Editor_) has no way to tell which of the three sections (or 'subdomains') an encountered restrictions payload should be assigned to, since the payload only identifies itself with the common domain string.

At DigiDNA, we have already considered the following solutions:
- A custom hidden 'subdomain' key could tell the software what section to associate the payoad with. This will not work for existing payloads nor for profiles created with other software (e.g. _Apple Configurator_)

- Detecting the right section by searching for platform-specific preference keys present in the payload. This will not work for payloads which only contain keys that are compatible with all subdomains. For example, a restrictions payload which only includes the `allowCamera` key.

Seeing as there is no reliable solution, I recommend that we merge the manifests back, and avoid clutter using existing features such as dividing keys into segments.

I'm happy to hear your thoughts about this.

Ari

**Comment by apizz** [comment]
This is a valid point.  Since ProfileCreator creates a separate file when saving that is different than an exported profile, it could be possible to specify something there, but since iMazing works directly with profiles I see the issue when trying to open them.

Looking at Apple's docs (https://developer.apple.com/documentation/devicemanagement/toplevel) there appears to be a `TargetDeviceType` key that's not currently used in either ProfileCreator or iMazing Profile Editor which specifies the OS (all or individual ones) that the profile can be used with to avoid unattended installations.

Currently, there is some logic in PC where if you have add a payload that's only for one OS, it won't let you add another payload that only works with a different OS.  Below you'll see I added Chrome (macOS only) and then tried to add iOS Restrictions.

![Screen Shot 2019-12-05 at 12 52 58 AM](https://user-images.githubusercontent.com/11789931/70207816-d128c800-16f9-11ea-9b9f-b1a4cf574b2b.png)

With something like that in place, I can imagine that you could safely write the `TargetDeviceType` and value when exporting your profile to indicate what OS the profile is intended for and then reference that when loading it.

```
0 = Any/unspecified

1 = iPhone/iPad/iPod Touch

2 = Apple Watch

3 = HomePod

4 = Apple TV

5 = Mac

Default: 0
Possible values: 0, 1, 2, 3, 4, 5
```

Let me know what you think, @relgit

**Comment by relgit** [comment]
Thanks for the feedback @apizz.

That's a good call in the case of the Restrictions domain, but I reckon it wouldn't work for the MCX one, as the split is not based on device OS although in that case key-name detection _would_ work.

Since we wanted to keep working directly with `.mobileconfig` files it came down to either re-merging the subdomains, or going with combined logic from both of the proposed solutions, i.e. a `TargetDeviceType` key for domains split based on device OS, and key-name detection for the others.

In the end, re-merging seemed like the most straight-forward solution for our needs, so in IPE the split domains are now merged back. We are merging dynamically with a script, so this allows us to factor in updates from the community and also to make our own contributions back like #194, which was made on the split files of MCX.

Since we have a working solution I'm going to close this request at that, but if ever there's interest in the community to re-merge the subdomains, we are happy to commit our merged ones.
