### ISSUE TITLE
Update to Microsoft Auto Update Channel Name values

### ISSUE THREAD

**Issue by bp88** [ProfileCreator/ProfileManifests#373]
### Please provide the following information:

**Name of App / Payload**: com.microsoft.autoupdate2

**Preference key(s) to be added / updated**: ChannelName
Old values: Production, External , and InsiderFast
New values: Current, Preview, and Beta

**Applicable Preference Documentation URL(s)**:
https://macadmins.slack.com/archives/C07UZ1X7B/p1603128077209900

**Comment by timnottom** [comment]
Hi, would it be helpful if I would create a pull request for this? The name change seems to be documented [here](https://docs.microsoft.com/en-us/deployoffice/update-channels-changes) and [here](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-updates?view=o365-worldwide). I think changing names in the [plist](https://github.com/ProfileCreator/ProfileManifests/blob/master/Manifests/ManagedPreferencesApplications/com.microsoft.autoupdate2.plist) at line 171, 181, 188,189 and 190 would suffice?

**Comment by apizz** [comment]
@timnottom thanks for this!  At the time this was posted I hadn't found any formal documentation that clearly defined and mapped old channel names to the new ones, and why I hadn't added this yet given the only reference was in the MacAdmins slack.  But this does so clearly: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-updates?view=o365-worldwide#set-the-channel-name.

I think to help with compatibility it would better to leave the existing channel values but update the display names so that it differentiates those pre/post AutoUpdate v4.29.

I'll get that updated quickly.

**Comment by timnottom** [comment]
Thank you for the changes @apizz ! 

The note now says: "Microsoft AutoUpdate pre 4.29 had different update channel names. While these still work post 4.29, it's recommended to use the new values if using MAU 4.29 or later"
But I found that the "still work" is not the case, as shown in the screenshots. 

InsiderFast and External no longer work. Production might not work, but since it's the same as Current this should not be an issue as Current seems to be the default if the string (like with InsiderFast and External) is unknown/not understood.

Could be that the old and the new names both worked in the past but it seems that the old ones are no longer working.
<img width="985" alt="Beta Screenshot 2022-01-05 at 21 42 03" src="https://user-images.githubusercontent.com/54109523/148288735-bf76838d-b0c5-4273-ae5c-14b8e46e9f95.png">
<img width="985" alt="Preview Screenshot 2022-01-05 at 21 42 44" src="https://user-images.githubusercontent.com/54109523/148288743-ef87b602-24a1-47c8-84b7-6e2e946078de.png">
<img width="985" alt="Current Screenshot 2022-01-05 at 21 43 43" src="https://user-images.githubusercontent.com/54109523/148288750-eeaa4edd-891a-4a10-ae0e-9703dc13c053.png">
<img width="985" alt="InsiderFast Screenshot 2022-01-05 at 21 44 16" src="https://user-images.githubusercontent.com/54109523/148288751-78da1d7f-21e1-4c63-bb14-579c2af19ce4.png">
<img width="985" alt="External Screenshot 2022-01-05 at 21 45 54" src="https://user-images.githubusercontent.com/54109523/148288755-391f2397-2e63-4b01-be4a-d67a057ec29e.png">
<img width="985" alt="Production Screenshot 2022-01-05 at 21 46 19" src="https://user-images.githubusercontent.com/54109523/148288758-196bcd0f-f638-405d-a03e-b64d07f8162e.png">

**Comment by apizz** [comment]
Will update the wording on this evening to avoid confusion.  Thanks for the thorough testing here!

**Comment by timnottom** [comment]
Thank you @apizz!!
