### ISSUE TITLE
PFM Review / pfm_documentation_url usage

### ISSUE THREAD

**Issue by ygini** [ProfileCreator/ProfileManifests#402]
The key `pfm_documentation_url` is supposed to contain a link to the official Apple's documentation for the related key / profile.

Most of the key and profile don't really use it, it could be a good improvement to generalize this usage.

And also, it could be really nice to be sure it actually link to the documentation, and not something else…

Like for example `com.apple.applicationaccess-macOS` / `pfm_subkeys` / Item 29 which point to the Jamf Pro 10.20.0 release notes…

The same issue is in `com.apple.applicationaccess-iOS` / `pfm_subkeys` / Item 27 and 40

**Comment by relgit** [comment]
A significant part of the knowledge in ProfileManifests comes not from official documentation but from experience of admins in the community, who find these keys in technical notes, third-party release notes, or through experimentation.

In the first example that you provided, the property in question `allowDeprecatedWebKitTLS`, is not present in the official documentation at least as of me writing this. The person who added that key to the repo (@apizz, I believe) used `pfm_documentation_url` to link back to the source where this information came from.

While in iMazing Profile Editor we are currently not exposing the documentation URL to users, it has been useful for us in a number of occasions already and I prefer keeping it as it is.

@apizz, your thoughts?

**Comment by ygini** [comment]
I agree regarding crowdsourced knowledge, that's mandatory for managed preferences.

It's a bit odd however for native keys, especially supposed by Apple, such as `allowDeprecatedWebKitTLS`.

I guess adding the Jamf link to the original commit where this key have been added make sense, but adding it as `URL to additional documentation for the key or payload` is maybe less appropriate. Regarding the number of keys that do not have an URL, I guess it would be better to not point to something unrelated so consuming apps could trust and use this value.

**Comment by relgit** [comment]
Generally, the documentation URL at the root of manifests points to the official documentation. It is only property-level appearances of this key which may lead to unofficial documentation (which is what I believe you mean by 'unrelated').

We both agree that unofficial information is important, so I'm going to leave it where it is for now and close this issue. If having unofficial sources mixed with official ones is a concern for you, I suggest either ignoring property-level URLs, or comparing URL domains to those in `pfm_app_url`.

In regards to populating more configuration properties with `pfm_documentation_URL` keys, this would be very nice, but I'm not sure how feasible it is since in most documentation sources that I've encountered there is one web page per manifest, and not an individual URL per key. However, dictionary properties on Apple configuration manifests do indeed have each their own web page, and it could be great to have those in the repository.

The best way, at the end of the day, to get those URLs for the dictionary properties, or for any other properties that you may have URLs for into the repository, is to simply go ahead and submit a PR. If you have the time and the interest, I certainly encourage you to do so.

Thanks!
