### ISSUE TITLE
com.apple.AppSSOKerberos.KerberosExtension

### ISSUE THREAD

**Issue by gbica-hzo** [ProfileCreator/ProfileManifests#556]
### Please provide the following information:

**App Name**: *Kerberos SSO Extension*

**App URL**: *https://support.apple.com/en-kw/guide/deployment/dep13c5cfdf9/web*

**App Profile Documentation URL**: *N/A*

**Payload / Domain**: *com.apple.AppSSOKerberos.KerberosExtension*

[com.apple.AppSSOKerberos.KerberosExtension.plist.txt](https://github.com/ProfileCreator/ProfileManifests/files/9235805/com.apple.AppSSOKerberos.KerberosExtension.plist.txt)

**Comment by gbica-hzo** [comment]
I already created a sample, attached to the case.

**Comment by relgit** [comment]
Hey @gbica-hzo and thanks for your submission.

Kerberos SSO preferences are available, however instead of having their own independent manifest they are actually a subset of the _Single Sign-On Extensions_ manifest which you can find over here:
https://github.com/ProfileCreator/ProfileManifests/blob/master/Manifests/ManifestsApple/com.apple.extensiblesso.plist

Your sample is a valid configuration profile, but notice how its `PayloadType` is `com.apple.extensiblesso`, and that `com.apple.AppSSOKerberos.KerberosExtension` is the value of the `ExtensionIdentifier` key.

I know this was submitted a few weeks ago, but if you're looking for some help on configuring Kerberos SSO, come visit us on the MacAdmins Slack #profiles channel where you'll find lots of great people happy to help.
